server:
  port: 8443

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:9443/oauth2/jwks

spiffe:
  workload:
    id: "spiffe://example.org/messages/resource-server"
    accepted-ids: "spiffe://example.org/messages/client, spiffe://example.org/messages/authorization-server"
