# debug: true
server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG


spring:
  ssl:
    bundle:
      jks:
        demo-client:
          key:
            alias: demo-client-sample
            password: password
          keystore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
          truststore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
        self-signed-demo-client:
          key:
            alias: self-signed-demo-client-sample
            password: password
          keystore:
            location: classpath:keystore-self-signed.p12
            password: password
            type: PKCS12
          truststore:
            location: classpath:keystore-self-signed.p12
            password: password
            type: PKCS12
  security:
    oauth2:
      client:
        registration:
          private-key-jwt-messaging-client-client-credentials:
            provider: spring
            client-id: messaging-client
            client-authentication-method: private_key_jwt
            authorization-grant-type: client_credentials
            scope: message.read,message.write
            client-name: private-key-jwt-messaging-client-client-credentials
        provider:
          spring:
            issuer-uri: http://localhost:9000
          spring-tls:
            token-uri: https://localhost:9443/oauth2/token

messages:
  base-uri: https://127.0.0.1:8443/messages
