= Samples

[[default-sample]]
== Default Sample

The default sample provides the minimal configuration to get started with Spring Authorization Server.

[[demo-sample]]
== Demo Sample

The demo sample provides a reference implementation of RFC 8705 OAuth 2.0 Mutual-TLS Client Authentication and Certificate-Bound Access Tokens
and demonstrates how to integrate Spring Authorization Server, Spring Security OAuth2 Client and Resource Server with SPIRE.

=== Setup SPIRE

* Download SPIRE -> `git clone git@github.com:spiffe/spire.git`
* Checkout tag v1.8.7 -> `git checkout -b v1.8.7 v1.8.7`
* Build SPIRE -> `make build`

=== Run SPIRE Server and Agent

* Run SPIRE Server -> `./bin/spire-server run -config conf/server/server.conf`
* Generate Join Token for SPIRE Agent -> `./bin/spire-server token generate -spiffeID spiffe://example.org/messages`
* Run SPIRE Agent -> `./bin/spire-agent run -config conf/agent/agent.conf -joinToken TOKEN_FROM_PREVIOUS_CMD`
* Register Workload Entries (one-time only):
** `./bin/spire-server entry create -parentID spiffe://example.org/messages -spiffeID spiffe://example.org/messages/authorization-server -selector unix:uid:$(id -u)`
** `./bin/spire-server entry create -parentID spiffe://example.org/messages -spiffeID spiffe://example.org/messages/resource-server -selector unix:uid:$(id -u)`
** `./bin/spire-server entry create -parentID spiffe://example.org/messages -spiffeID spiffe://example.org/messages/client -selector unix:uid:$(id -u)`
* Add SPIFFE Root Certificate to local keychain (one-time only):
** Add the SPIFFE Root Certificate (`spiffe/pki/spiffe-root-ca.pem`) using the Keychain Access app on your Mac and set it to "Always Trust".

=== Run the Sample

* Run Authorization Server -> `./gradlew -b samples/demo-authorizationserver/samples-demo-authorizationserver.gradle bootRun`
* Run Client -> `./gradlew -b samples/demo-client/samples-demo-client.gradle bootRun`
* Run Resource Server -> `./gradlew -b samples/messages-resource/samples-messages-resource.gradle bootRun`
* Go to `http://127.0.0.1:8080`
** Login with credentials -> user1 \ password

== References

* https://datatracker.ietf.org/doc/html/rfc8705[RFC 8705 - OAuth 2.0 Mutual-TLS Client Authentication and Certificate-Bound Access Tokens]
* https://spiffe.io/docs/latest/spiffe-about/overview/[SPIFFE]
* https://spiffe.io/docs/latest/spire-about/[SPIRE]
* https://github.com/spiffe/java-spiffe[Java SPIFFE Library]
