= Samples

[[default-sample]]
== Default Sample

The default sample provides the minimal configuration to get started with Spring Authorization Server.

[[demo-sample]]
== Demo Sample

The demo sample provides a reference implementation of https://datatracker.ietf.org/doc/html/rfc8705[RFC 8705 OAuth 2.0 Mutual-TLS Client Authentication and Certificate-Bound Access Tokens]
and demonstrates how to integrate Spring Authorization Server, Spring Security OAuth2 Client and Resource Server.

=== Generate Keystore files (one-time only)

* Run PKI Generator -> `./gradlew -b samples/pki-generator/samples-pki-generator.gradle bootRun`

=== Run the Sample

* Run Authorization Server -> `./gradlew -b samples/demo-authorizationserver/samples-demo-authorizationserver.gradle bootRun`
* Run Client -> `./gradlew -b samples/demo-client/samples-demo-client.gradle bootRun`
* Run Resource Server -> `./gradlew -b samples/messages-resource/samples-messages-resource.gradle bootRun`
* Go to `http://127.0.0.1:8080`
** Login with credentials -> user1 \ password
