server:
  ssl:
    enabled: true
    key-store: classpath:spring-resource-server.p12
    key-store-password: secret
    key-store-type: pkcs12
    key-alias: spring-resource-server
    key-password: secret
    client-auth: need
    trust-store: classpath:spring-resource-server.p12
    trust-store-password: secret
    trust-store-type: pkcs12
  port: 8443

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:  https://auth-server:9443/oauth2/jwks
